version: '2'

services:
  crowd-checked-postgres:
    image: 'postgres:10.3-alpine'
    volumes:
      - 'crowd-checked-postgres:/var/lib/postgresql/data'
    env_file:
      - '.env'

  crowd-checked-redis:
    image: 'redis:4.0-alpine'
    command: redis-server --requirepass yourpassword
    volumes:
      - 'crowd-checked-redis:/data'

  website:
    depends_on:
      - 'crowd-checked-postgres'
      - 'crowd-checked-redis'
      - 'crowd-checked-sidekiq'
    build: .
    ports:
      - '3002:3000'
    expose:
      - '3000'
    volumes:
      - '.:/app'
    env_file:
      - '.env'
    environment:
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_HOST=crowdchecked.com,www.crowdchecked.com
      - LETSENCRYPT_HOST=crowdchecked.com,www.crowdchecked.com
      - LETSENCRYPT_EMAIL=admin@crowdchecked.com
      - VIRTUAL_PORT=3002

  crowd-checked-sidekiq:
    depends_on:
      - 'crowd-checked-postgres'
      - 'crowd-checked-redis'
    build: .
    command: sidekiq -C config/sidekiq.yml.erb
    volumes:
      - '.:/app'
    env_file:
      - '.env'

volumes:
  crowd-checked-redis:
  crowd-checked-postgres:

networks:
  default:
    external:
      name: nginx-proxy
